// angular-regular/src/app/components/user-filter/user-filter.component.ts
import {Component, EventEmitter, Input, Output} from '@angular/core';
import {FormsModule, ReactiveFormsModule} from "@angular/forms";

@Component({
  selector: 'app-user-filter',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    FormsModule
  ],
  templateUrl: './user-filter.component.html',
  styleUrl: './user-filter.component.css'
})
export class UserFilterComponent {
  @Input()
  selectedUser: string = '';
  @Input()
  users: string[] = [];
  @Output()
  userChanged: EventEmitter<string> = new EventEmitter<string>();

  updateSelectedUser(user: string) {
    this.userChanged.emit(user);
  }
}

<div class="flex flex-col">
  <label for="user-filter" class="mb-1 text-sm font-medium text-gray-700">Usuario</label>
  <select
    id="user-filter"
    [ngModel]="selectedUser"
    (ngModelChange)="updateSelectedUser($event)"
    class="w-full sm:w-40 bg-white text-sm rounded-lg px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-800"
  >
    <option value="">Todos</option>
    @for(user of users; track $index) {
      <option [value]="user">
        {{ user }}
      </option>
    }
  </select>
</div>

// vue-good/src/components/filter/UserFilter.vue
<template>
  <div class="flex flex-col">
    <label for="user-filter" class="mb-1 text-sm font-medium text-gray-700">Usuario</label>
    <select
      id="user-filter"
      v-model="selectedUser"
      class="w-full sm:w-40 bg-white text-sm rounded-lg px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-gray-800"
    >
      <option value="">Todos</option>
      <option v-for="user in users" :key="user" :value="user">
        {{ user }}
      </option>
    </select>
  </div>
</template>

<script setup lang="ts">
import { computed, defineProps, defineEmits } from 'vue';

const props = defineProps<{
  users: string[];
  modelValue: string;
}>();

const emit = defineEmits(['update:modelValue']);

const selectedUser = computed({
  get: () => props.modelValue,
  set: (value: string) => emit('update:modelValue', value),
});
</script>
