// vue-good/src/components/TodoList.vue
<template>
  <div class="min-h-screen bg-gray-100 flex justify-center items-start py-12">
    <div class="w-full max-w-3xl bg-white shadow-lg rounded-lg p-8">
      <h1 class="text-3xl font-bold mb-6 text-gray-900">Lista de tareas (Vue + TypeScript + Composable)</h1>

      <div class="mb-6">
        <div class="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
          <UserFilter :users="users" v-model="selectedUser" />
          <StatusFilter v-model="filter" />
        </div>
      </div>

      <div class="flex flex-row gap-2 items-center">
        <TodoInput @add-todo="addTodo" />
      </div>

      <div class="space-y-3 mt-4">
        <TodoItem
          v-for="(todo) in todos"
          :key="todo.id"
          :todo="todo"
          :users="users"
          @toggle-completed="toggleCompleted"
          @update-text="updateText"
          @update-user="updateUser"
          @delete-todo="deleteTodo"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import TodoInput from './TodoInput.vue';
import TodoItem from './TodoItem.vue';
import UserFilter from './UserFilter.vue';
import StatusFilter from './StatusFilter.vue';
import useTodosNonOptimized from '@/composables/useTodosNonOptimized';

const users = ref<string[]>(['Manu', 'Cris', 'Bob']);
const selectedUser = ref('');
const filter = ref('');

const {
  todos,
  addTodo,
  toggleCompleted,
  updateText,
  updateUser,
  deleteTodo,
} = useTodosNonOptimized(selectedUser, filter);
</script>

// react-good/src/scenes/TodoList/TodoList.tsx
'use client';

import { FC, useState } from 'react';

import { StatusFilter } from '@/components/filter/StatusFilter';
import { UserFilter } from '@/components/filter/UserFilter';
import { TodoInput } from '@/components/todo/TodoInput';
import { TodoItem } from '@/components/todo/TodoItem';
import { useTodos } from '@/hooks/useTodos';
import { Todo } from '@/types/Todo';

export const TodoList: FC = () => {
  const [newTodo, setNewTodo] = useState('');
  const [users] = useState<string[]>(['Manu', 'Cris', 'Bob']);
  const [selectedUser, setSelectedUser] = useState('');
  const [filter, setFilter] = useState('');

  const { todos, addTodo, updateTodo, deleteTodo } = useTodos({
    selectedUser,
    filter,
  });

  const handleAddTodo = async () => {
    await addTodo(newTodo);
    setNewTodo('');
  };

  const toggleCompleted = (todo: Todo) => {
    updateTodo(todo.id, { completed: !todo.completed });
  };

  const updateText = (todo: Todo, newText: string) => {
    updateTodo(todo.id, { text: newText });
  };

  const updateUser = (todo: Todo, user: string) => {
    if (user !== todo.user) {
      updateTodo(todo.id, { user });
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 flex justify-center items-start py-12">
      <div className="w-full max-w-3xl bg-white shadow-lg rounded-lg p-8">
        <h1 className="text-2xl font-bold mb-6 text-gray-900">
          Lista de tareas (React + TypeScript + Hook)
        </h1>

        <div className="mb-6">
          <div className="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
            <UserFilter
              users={users}
              selectedUser={selectedUser}
              onUserChange={setSelectedUser}
            />
            <StatusFilter filter={filter} onFilterChange={setFilter} />
          </div>
        </div>

        <div className="flex flex-row gap-2 items-center">
          <TodoInput
            newTodo={newTodo}
            setNewTodo={setNewTodo}
            addTodo={handleAddTodo}
          />
        </div>

        <div className="space-y-3 mt-4">
          {todos.map((todo) => (
            <TodoItem
              key={todo.id}
              todo={todo}
              users={users}
              onToggleCompleted={toggleCompleted}
              onUpdateText={updateText}
              onUpdateUser={updateUser}
              onDeleteTodo={deleteTodo}
            />
          ))}
        </div>
      </div>
    </div>
  );
};
