// vue-regular/src/components/TodoList.vue
<template>
  <div class="space-y-3 mt-4">
    <TodoItem
      v-for="(todo, index) in todos"
      :key="index"
      :todo="todo"
      :index="index"
      :users="users"
      @toggle-completed="$emit('toggle-completed', $event)"
      @update-text="$emit('update-text', $event)"
      @update-user="$emit('update-user', $event.todo, $event.user)"
      @delete-todo="$emit('delete-todo', $event)"
      @start-edit="$emit('start-edit', $event)"
      @finish-edit="$emit('finish-edit', $event.index, $event.todo)"
    />
  </div>
</template>

<script>
import TodoItem from './TodoItem.vue';

export default {
  name: 'TodoList',
  components: {
    TodoItem,
  },
  props: {
    todos: Array,
    users: Array,
  },
};
</script>

// react-regular/src/components/TodoList.jsx
import React from 'react';
import TodoItem from './TodoItem';

function TodoList({
  todos,
  users,
  toggleCompleted,
  updateText,
  updateUser,
  deleteTodo,
  startEdit,
  finishEdit,
  editInputRef,
  setTodos,
}) {
  return (
    <div className="space-y-3 mt-4">
      {todos.map((todo, index) => (
        <TodoItem
          key={todo.id}
          todo={todo}
          index={index}
          todos={todos}
          users={users}
          toggleCompleted={toggleCompleted}
          updateText={updateText}
          updateUser={updateUser}
          deleteTodo={deleteTodo}
          startEdit={startEdit}
          finishEdit={finishEdit}
          editInputRef={editInputRef}
          setTodos={setTodos}
        />
      ))}
    </div>
  );
}

export default TodoList;
