// vue-good/src/App.vue
<script setup lang="ts">
import TodoList from '@/views/TodoList/TodoList.vue';
// import TodoListWithLogic from '@/views/TodoList/TodoListWithLogic.vue';

</script>

<template>
  <div className="min-h-screen w-full bg-gray-100 flex">
    <div className="w-full p-4">
      <TodoList />
    </div>
  </div>
</template>

// react-good/src/app/page.tsx
import { TodoList } from "@/scenes/TodoList";
// import { TodoListWithLogic } from "@/scenes/TodoList";

export default function Home() {
  return (
    <div className="min-h-screen w-full bg-gray-100 flex">
      <div className="w-full p-4">
        <TodoList />
        {/* <TodoListWithLogic /> */}
      </div>
    </div>
  );
}
